User.create!([
  {username: "joe", email: "joe@gmail.com", password_digest: "$2a$10$Ubl.3/va2JlE0QIaG235tOn9K4upzuKc0Ikrwjzf.dAoUJAIwT5cW"},
  {username: "joseph", email: "joseph@gmail.com", password_digest: "$2a$10$Qj9MEiv/p4KAYUQYPngq3OLemx.zHL8kSWqidvwbGliMnQnaeVW4K"},
  {username: "jerry", email: "jerry@gmail.com", password_digest: "$2a$10$OvIagK/yk1ISR4bKzL.KeOGYoQBWoAfyy.awoHCFXE2kvgFDYe0aO"},
  {username: "kait", email: "kait@gmail.com", password_digest: "$2a$10$A7u.0LDe8Rhs6M8WNvHpBufN48GyE/ceBVpxrlmwPHx9I5oREZLXm"}
])
Tile.create!([
  {path: "empty"},
  {path: "curve hallway small"},
  {path: "room"},
  {path: "square curve"},
  {path: "inverse curve"},
  {path: "circle curve"},
  {path: "circle edge"},
  {path: "circle edge closed"},
  {path: "circle edge closed 2"},
  {path: "square edge"},
  {path: "rectangle room"},
  {path: "square room"},
  {path: "curve corner"},
  {path: "curve half closed room"},
  {path: "curve room closed"},
  {path: "long hallway"},
  {path: "full tile"},
  {path: "diagonal hallway"},
  {path: "diagonal hallway part closed"},
  {path: "diagonal hallway two part closed"},
  {path: "diagonal hallway fat"},
  {path: "diagonal hallway fat part closed"},
  {path: "diagonal hallway fat two part closed"},
  {path: "three part hallway rectangle"},
  {path: "three part hallway curved"},
  {path: "wide curve room"},
  {path: "wide curve room closed"},
  {path: "wide hall straight"},
  {path: "wide hall straight 2"},
  {path: "wide hall straight 3"},
  {path: "wide hall straight room"},
  {path: "wide hall thin tip"},
  {path: "wide hall thin tip 2"},
  {path: "wide hall thin tip 3"},
  {path: "wide hall thin tip room"},
  {path: "wide hall curve corner"},
  {path: "wide hall curve corner 2"},
  {path: "wide hall curve corner 3"},
  {path: "wide hall curve corner room"},
  {path: "wide hall indent corner"},
  {path: "wide hall indent corner 2"},
  {path: "wide hall indent corner 3"},
  {path: "wide hall indent corner room"},
  {path: "wide room double curve"},
  {path: "wide room double indent"},
  {path: "wide room double indent 2"},
  {path: "large room double curve"},
  {path: "large room double indent"},
  {path: "large room double curve 2"},
  {path: "large room double indent 2"},
  {path: "large room double curve 3"},
  {path: "large room double indent 3"},
  {path: "large room double curve 4"},
  {path: "large room double indent 4"},
  {path: "hallway square end"},
  {path: "hallway square end 2"},
  {path: "hallway square end 3"},
  {path: "hallway square end 4"},
  {path: "full tile with corner"},
  {path: "full tile with corner 2"},
  {path: "full tile with corner 3"},
  {path: "full tile with corner 4"},
  {path: "full tile with corner 5"},
  {path: "full tile with corner 6"},
  {path: "full tile with corner 7"},
  {path: "full tile with corner 8"},
  {path: "room small"},
  {path: "skinny hallway"},
  {path: "skinny curve hallway"},
  {path: "skinny curve hallway 2"},
  {path: "three way hallway skinny"},
  {path: "four way hallway"},
  {path: "full tile 2"},
  {path: "full tile 3"},
  {path: "large tile"},
  {path: "large tile 2"},
  {path: "large tile 3"},
  {path: "circle curve up"},
  {path: "circle curve left"},
  {path: "circle curve down"},
  {path: "circle edge up"},
  {path: "circle edge left"},
  {path: "circle edge down"},
  {path: "circle edge closed up"},
  {path: "circle edge closed left"},
  {path: "circle edge closed down"},
  {path: "circle edge closed 2 up"},
  {path: "circle edge closed 2 left"},
  {path: "circle edge closed 2 down"},
  {path: "curve corner up"},
  {path: "curve corner left"},
  {path: "curve corner down"},
  {path: "curve half closed room up"},
  {path: "curve half closed room left"},
  {path: "curve half closed room down"},
  {path: "curve hallway small up"},
  {path: "curve hallway small left"},
  {path: "curve hallway small down"},
  {path: "curve room closed up"},
  {path: "curve room closed left"},
  {path: "curve room closed down"},
  {path: "diagonal hallway up"},
  {path: "diagonal hallway fat up"},
  {path: "diagonal hallway fat part closed up"},
  {path: "diagonal hallway fat two part closed up"},
  {path: "full tile 2 up"},
  {path: "full tile 2 left"},
  {path: "full tile 2 down"},
  {path: "full tile 3 down"},
  {path: "full tile with corner up"},
  {path: "full tile with corner left"},
  {path: "full tile with corner down"},
  {path: "full tile with corner 2 up"},
  {path: "full tile with corner 2 left"},
  {path: "full tile with corner 2 down"},
  {path: "full tile with corner 3 up"},
  {path: "full tile with corner 3 left"},
  {path: "full tile with corner 3 down"},
  {path: "full tile with corner 5 up"},
  {path: "full tile with corner 5 left"},
  {path: "full tile with corner 5 down"},
  {path: "full tile with corner 6 up"},
  {path: "full tile with corner 6 left"},
  {path: "full tile with corner 6 down"},
  {path: "full tile with corner 7 down"},
  {path: "full tile with corner 7 up"},
  {path: "full tile with corner 7 left"},
  {path: "full tile with corner 8 left"},
  {path: "full tile with corner 8 down"},
  {path: "full tile with corner 8 up"},
  {path: "hallway square end up"},
  {path: "hallway square end left"},
  {path: "hallway square end down"},
  {path: "hallway square end 2 up"},
  {path: "hallway square end 2 left"},
  {path: "hallway square end 2 down"},
  {path: "hallway square end 3 down"},
  {path: "hallway square end 3 left"},
  {path: "hallway square end 3 up"},
  {path: "hallway square end 4 up"},
  {path: "hallway square end 4 left"},
  {path: "hallway square end 4 down"},
  {path: "inverse curve left"},
  {path: "inverse curve down"},
  {path: "large room double curve up"},
  {path: "large room double curve down"},
  {path: "large room double curve left"},
  {path: "large room double curve 2 left"},
  {path: "large room double curve 2 down"},
  {path: "large room double curve 2 up"},
  {path: "large room double curve 3 up"},
  {path: "large room double curve 3 down"},
  {path: "large room double curve 3 left"},
  {path: "large room double curve 4 left"},
  {path: "large room double curve 4 up"},
  {path: "large room double curve 4 down"},
  {path: "large room double indent down"},
  {path: "large room double indent left"},
  {path: "large room double indent up"},
  {path: "large room double indent 2 up"},
  {path: "large room double indent 2 left"},
  {path: "large room double indent 2 down"},
  {path: "large room double indent 3 down"},
  {path: "large room double indent 3 left"},
  {path: "large room double indent 3 up"},
  {path: "large room double indent 4 up"},
  {path: "large room double indent 4 left"},
  {path: "large room double indent 4 down"},
  {path: "large tile down"},
  {path: "large tile left"},
  {path: "large tile up"},
  {path: "large tile 2 up"},
  {path: "large tile 2 left"},
  {path: "large tile 2 down"},
  {path: "large tile 3 down"},
  {path: "large tile 3 left"},
  {path: "large tile 3 up"},
  {path: "long hallway left"},
  {path: "rectangle room up"},
  {path: "rectangle room left"},
  {path: "rectangle room down"},
  {path: "room down"},
  {path: "room left"},
  {path: "room up"},
  {path: "room small up"},
  {path: "room small left"},
  {path: "room small down"},
  {path: "skinny curve hallway down"},
  {path: "skinny curve hallway left"},
  {path: "skinny curve hallway up"},
  {path: "skinny curve hallway 2 up"},
  {path: "skinny curve hallway 2 left"},
  {path: "skinny curve hallway 2 down"},
  {path: "skinny hallway left"},
  {path: "square curve down"},
  {path: "square curve left"},
  {path: "square curve up"},
  {path: "square edge up"},
  {path: "square edge left"},
  {path: "square edge down"},
  {path: "square room down"},
  {path: "square room left"},
  {path: "square room up"},
  {path: "three part hallway curved down"},
  {path: "three part hallway curved left"},
  {path: "three part hallway curved up"},
  {path: "three part hallway rectangle up"},
  {path: "three part hallway rectangle left"},
  {path: "three part hallway rectangle down"},
  {path: "three way hallway skinny down"},
  {path: "three way hallway skinny left"},
  {path: "three way hallway skinny up"},
  {path: "wide curve room down"},
  {path: "wide curve room left"},
  {path: "wide curve room up"},
  {path: "wide curve room closed up"},
  {path: "wide curve room closed left"},
  {path: "wide curve room closed down"},
  {path: "wide hall curve corner down"},
  {path: "wide hall curve corner up"},
  {path: "wide hall curve corner left"},
  {path: "wide hall curve corner 2 left"},
  {path: "wide hall curve corner 2 up"},
  {path: "wide hall curve corner 2 down"},
  {path: "wide hall curve corner 3 down"},
  {path: "wide hall curve corner 3 left"},
  {path: "wide hall curve corner 3 up"},
  {path: "wide hall curve corner room up"},
  {path: "wide hall curve corner room left"},
  {path: "wide hall curve corner room down"},
  {path: "wide hall indent corner down"},
  {path: "wide hall indent corner left"},
  {path: "wide hall indent corner up"},
  {path: "wide hall indent corner 2 up"},
  {path: "wide hall indent corner 2 left"},
  {path: "wide hall indent corner 2 down"},
  {path: "wide hall indent corner 3 down"},
  {path: "wide hall indent corner 3 left"},
  {path: "wide hall indent corner 3 up"},
  {path: "wide hall indent corner room up"},
  {path: "wide hall indent corner room left"},
  {path: "wide hall indent corner room down"},
  {path: "wide hall straight down"},
  {path: "wide hall straight left"},
  {path: "wide hall straight up"},
  {path: "wide hall straight 2 up"},
  {path: "wide hall straight 2 left"},
  {path: "wide hall straight 2 down"},
  {path: "wide hall straight 3 down"},
  {path: "wide hall straight 3 left"},
  {path: "wide hall straight 3 up"},
  {path: "wide hall straight room up"},
  {path: "wide hall straight room left"},
  {path: "wide hall straight room down"},
  {path: "wide hall thin tip down"},
  {path: "wide hall thin tip left"},
  {path: "wide hall thin tip up"},
  {path: "wide hall thin tip 2 up"},
  {path: "wide hall thin tip 2 left"},
  {path: "wide hall thin tip 2 down"},
  {path: "wide hall thin tip 3 down"},
  {path: "wide hall thin tip 3 left"},
  {path: "wide hall thin tip 3 up"},
  {path: "wide hall thin tip room up"},
  {path: "wide hall thin tip room left"},
  {path: "wide hall thin tip room down"},
  {path: "wide room double curve down"},
  {path: "wide room double curve up"},
  {path: "wide room double curve left"},
  {path: "wide room double curve 2 left"},
  {path: "wide room double curve 2 down"},
  {path: "wide room double curve 2 up"},
  {path: "wide room double indent up"},
  {path: "wide room double indent left"},
  {path: "wide room double indent down"},
  {path: "wide room double indent 2 down"},
  {path: "wide room double indent 2 left"},
  {path: "wide room double indent 2 up"},
  {path: "inverse curve up"}
])
Journey.create!([
  {name: "help", description: "please work", dm_id: 3},
  {name: "Here", description: "We go", dm_id: 3},
  {name: "The Hobbit", description: "It always starts with a ring", dm_id: 1},
  {name: "Swamp", description: "trudging through the swamp", dm_id: 2},
  {name: "Kait's Quest", description: "Kait is on a quest.", dm_id: 4},
  {name: "New Journey", description: "Hooray", dm_id: 4},
  {name: "Matt's Quest", description: "We are all on a quest of our own but this one is Matt's", dm_id: 4},
  {name: "Space War", description: "It is a knock off version of star wars.", dm_id: 1}
])
Map.create!([
  {name: "3 x 3", description: "test map", row_number: 3, column_number: 3, creator_id: 1, journey_id: 8}
])
Participation.create!([
  {user_id: 1, journey_id: 4},
  {user_id: 4, journey_id: 4},
  {user_id: 1, journey_id: 5},
  {user_id: 2, journey_id: 5},
  {user_id: 1, journey_id: 6},
  {user_id: 1, journey_id: 7},
  {user_id: 4, journey_id: 3},
  {user_id: 4, journey_id: 8},
  {user_id: 2, journey_id: 8}
])
Placement.create!([
  {row: 2, column: 2, map_id: 1, tile_id: 1},
  {row: 3, column: 3, map_id: 1, tile_id: 1},
  {row: 2, column: 2, map_id: 1, tile_id: 1},
  {row: 3, column: 3, map_id: 1, tile_id: 1},
  {row: 1, column: 1, map_id: 1, tile_id: 1},
  {row: 2, column: 2, map_id: 1, tile_id: 1},
  {row: 3, column: 3, map_id: 1, tile_id: 1},
  {row: 1, column: 1, map_id: 1, tile_id: 89},
  {row: 1, column: 1, map_id: 1, tile_id: 186}
])


